---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/products/{id}":
    put:
      summary: Updates a product
      tags:
      - Products
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: product updated
        '404':
          description: product not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                description:
                  type: string
              required:
              - name
              - price
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
